config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get 'welcome/index'
  get 'about' => 'welcome#about'
  root 'welcome#index'
  
  resources :wikis
  
  resources :charges, only: [:new, :create, :destroy] do
    get '/thanks' => 'charges#thanks', as: :thanks
    get '/goodbye' => 'charges#goodbye', as: :goodbye
  end
  
  

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
 has_many :collaborators
 has_many :wikis, through: :collaborators
  
  
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  enum role: [:standard, :premium, :admin]
  after_initialize { self.role ||= :standard }
  
  
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user

  has_many :collaborators
  has_many :users, through: :collaborators
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  
  private
  
  
  def user_not_authorized
  
    flash[:notice] = "Not authorized to make that change."
    redirect_to edit_wiki_path
  end
  
  def change_plan(current_user)
    if current_user.role == 'standard'
      User.where('email = ?', current_user.email).update_all(role: 1)
    elsif current_user.role == 'premium'
      User.where('email = ?', current_user.email).update_all(role: 0)
      Wiki.where('user_id = ?', current_user.id).update_all(private: false)
    end
  end

  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
     @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     #description: "BigMoney Membership - #{params[:stripeEmail]}",
     description: "BigMoney Membership - #{current_user.email}",
     amount: Amount.default
   }
end

def create
 
 
  customer = Stripe::Customer.create(
    email: current_user.email,
    source: params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    customer: customer.id,
    amount: Amount.default,
    description: "BigMoney Membership - #{current_user.email}",
    currency: 'usd'
  )
  
  change_plan(current_user)


 flash[:notice] = "Thanks for upgrading, #{current_user.email}!"

 #redirect_to charge_thanks_path(current_user)
  redirect_to wikis_path

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end

def destroy
  change_plan(current_user)
  flash[:alert] = "Your plan has been downgraded, #{current_user.email}."
  redirect_to wikis_path
  #redirect_to charge_goodbye_path(current_user)
end


private

class Amount
  def self.default
    return 500
  end
end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
    def index
        #@wikis = Wiki.all
        @wikis = policy_scope(Wiki)
    end
    
    def show
        @wiki = Wiki.find(params[:id])
    end
    
    def new
        @wiki = Wiki.new
    end
    
    def create
        @wiki = Wiki.new
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        @wiki.user_id = current_user.id

        
        if @wiki.save
            redirect_to @wiki, notice: "Wiki was saved successfully."
        else
            flash.now[:alert] = "Error creating Wiki topic. Please try again."
            render :new
        end
    end
    
    def edit
        @wiki = Wiki.find(params[:id])
    end
    
    def update
        @wiki = Wiki.find(params[:id])
        authorize @wiki
        
        @wiki.title = params[:wiki][:title]
        @wiki.body = params[:wiki][:body]
        @wiki.private = params[:wiki][:private]
        
        
        @add_collaborators = params[:add_collaborators]
        addCollaborators(@add_collaborators, @wiki.id)
        
        @remove_collaborators = params[:remove_collaborators]
        removeCollaborators(@remove_collaborators, @wiki.id)
        
        
        if @wiki.save
            flash[:notice] = "Wiki was updated."
            redirect_to @wiki
        else
            flash.now[:alert] = "Error saving wiki. Please try again."
            render :edit
        end
    end
    
    def destroy
        @wiki = Wiki.find(params[:id])
        
        if @wiki.destroy
            flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
            redirect_to action: :index
        else
            flash.now[:alert] = "There was an error deleting the Wiki."
            render :show
        end
    end
    
    private
    
    def addCollaborators(emails, wiki_id)
        email_list = emails.split(";")
        email_list.each do |email|
            if Collaborator.where("email = ? AND wiki_id = ?", email, wiki_id).count == 0
                Collaborator.create(user_id: User.where("email = ?", email).pluck(:id).first, wiki_id: wiki_id, email: email)
            end
        end
    end
    
    
    def removeCollaborators(emails, wiki_id)
        email_list = emails.split(";")
        email_list.each do |email|
            if Collaborator.where("email = ? AND wiki_id = ?", email, wiki_id).count > 0
                Collaborator.where("email = ? AND wiki_id = ?", email, wiki_id).destroy_all
            end
        end
    end
    
    
    
    
end

app/helpers/application_helper.rb
require 'redcarpet'
module ApplicationHelper
    def markdown(text)
        options = {
            hard_wrap:              true, 
            filter_html:            true, 
            autolink:               true, 
            no_intra_emphasis:      true, 
            fenced_code_blocks:     true,
            space_after_headers:    true
        }
        
        extensions = {
            autolink:           true,
            superscript:        true,
            disable_indented_code_blocks: true
        }
    
        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
        
        markdown.render(text).html_safe
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<div class="chg-indent">
<%= form_tag charges_path do %>
   <h4>Pay now to upgrade <br> to our premium plan.</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
       <li><%= link_to "Blocipedia", welcome_index_path %></li>
       <li><%= link_to "About", about_path %></li>
       <li><%= link_to "Wikis", wikis_path %></li>
       <% if user_signed_in? %>
            
            <div class="sign-in-as">
               Signed in as: <strong><%= current_user.email %></strong>
            </div>
            
            <li>
               <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> 
            </li>
            <li>
               <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
            </li>          
         <% else %>
            <li>
               <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> 
            </li>
            <li>
               <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
            </li>
         <% end %>
    </ul>
  </div>


<% if flash[:notice] %>
   <div class="alert alert-success">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:notice] %>
   </div>
<% elsif flash[:alert] %>
   <div class="alert alert-warning">
     <button type="button" class="close" data-dismiss="alert">&times;</button>
     <%= flash[:alert] %>
   </div>
 <% end %>         
       
  
  
  
<%= yield %>


</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<section class="pageIndent">
<h1>Edit Wiki</h1>
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for wiki topics:</p>
     <ul>
       <li>Make sure the wiki topic is appropriate.</li>
       <li>Try not to be boring.</li>
       <li>Try not to pull stuff from air.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter title name" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>

       <%= render partial: 'form', locals: {f: f} %>
       
            
      <div class="form-group">
         <%= label(:add_collaborators, 'Add Collaborators') %>
          <p>Add collaborators by typing in the collaborator's email address. To add multiple collaborators, separate emails with "<strong>;</strong>".</p>
          <br>
         <%= text_area_tag :add_collaborators,  @add_collaborators, :size =>"100x2.5" %>
      </div>
      
      <div class="form-group">
         <%= label(:remove_collaborators, 'Remove Collaborators') %>
          <p>Remove collaborators by typing in the collaborator's email address. To remove multiple collaborators, separate emails with "<strong>;</strong>".</p>
          <br>
         <%= text_area_tag :remove_collaborators,  @remove_collaborators, :size =>"100x2.5" %>
      </div>
         
       
       <%= f.submit "Save", class: 'btn btn-default' %>
     <% end %>
   </div>
 </div>
</section>

app/views/wikis/index.html.erb
<section class="pageIndent">
    <h1>Wikis</h1> 
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-default' %>
    <br>
    <br>
<div class="row">
    <% @wikis.each do |wiki| %>
    <div class="col-md-8">
        <h4 class="media-heading">
            <%= link_to wiki.title, wiki %>
        </h4>
    </div>
    <div class="col-md-1">
          <%= link_to "Edit Wiki", edit_wiki_path(wiki), class: 'btn btn-link' %>
    </div>
    <div class="col-md-1">
          <%= link_to "Delete Wiki", wiki, method: :delete, class: 'btn btn-link', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
    </div>
  <% end %>
</div>
</section>

app/views/wikis/new.html.erb
<section class="pageIndent">
<h1>New Wiki</h1>
<div class="row">
   <div class="col-md-4">
     <p>Guidelines for wikis:</p>
     <ul>
       <li>Make sure the wiki topic is appropriate.</li>
       <li>Try not to be boring.</li>
       <li>Try not to pull stuff from air.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter Wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter Wiki body" %>
       </div>
       <%= render partial: 'form', locals: {f: f} %>
       <%= f.submit "Save", class: 'btn btn-default' %>
     <% end %>
     
     
   </div>
 </div>
</section>

app/views/wikis/show.html.erb
<section class="pageIndent">
    <h1><%= @wiki.title %></h1>
        <%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-default' %>
    <br>
    <br>
    
    <p><%= markdown(@wiki.body) %></p>
</section>